### ISSUE TITLE
[Bug] SmartListing 1.2.0 with Kaminari can't sort by x column when you will go to next/prev page

### ISSUE THREAD

**Issue by KamilDzierbicki** [Sology/smart_listing#129] opened 2017-08-16 13:47 UTC
When you will sort the first page by column x and you will go to the next/previous page, the sort will not be work correctly(link in pagination component doesn't have good URL).
Change from 1.2.0 to 0.16.3 will fix the problem

**Comment by ljachymczyk** [comment] 2017-10-03 11:53
Hello,
I've checked on our showcase - it runs SmartListing 1.2.1 and example with sorting and pagination seems to work for me: http://showcase.sology.eu/smart_listing#sorting
Can you provide some more details?

**Comment by ljachymczyk** [comment] 2018-01-10 11:43
Closing as a possible duplicate of #111

**Closed by ljachymczyk** 2018-01-10 11:43 UTC
