### ISSUE TITLE
Changing content class in config breaks gem

### ISSUE THREAD

**Issue by ZebThan** [Sology/smart_listing#74] opened 2015-12-07 13:29 UTC
I've changed the class name for content (in config), and the gem stoped working. With the default class names it works like a charm. Any idea how to work around it?

**Comment by ardahaal** [comment] 2015-12-07 14:26
Hello, thanks for noticing this bug. We will debug it and repair it. Please use default class name until then.

**Comment by ZebThan** [comment] 2015-12-07 14:39
It's not possible to use the default name, so I'm working on fixing this by myself. If by any chance I manage to fix it, I will make a pull request. It seems that the problem is in the assets/javascripts/smart_listing.coffee.erb in the line 34 (class name is hardcoded).

Unlucky, I'm rather bad at javascripts, so I don't really understands how it works :(
Anyway, thanks for the quick response.

**Comment by ardahaal** [comment] 2015-12-07 14:40
No problem, I'm working on this right now, so You can do other stuff:)

**Comment by ZebThan** [comment] 2015-12-07 14:42
Okay, thanks for your time then :)

**Comment by ardahaal** [comment] 2015-12-07 14:48
Ok, sorry to inform You, but i"ve just made a mistake and turns out that everything works as designed.
Good news now, I think I know where is Your mistake. Did You append data hash with smart_listing config to 'body' element? If not please do like this:

    %body{"data-smart-listing-config" => (SmartListing.config(smart_listing_config_profile).to_json if defined?(smart_listing_config_profile))}

Then You have to merge it in Javascript:

    SmartListing.config.merge();

I'm updating my smart_listing example right now and I'll sent You link.

**Comment by ZebThan** [comment] 2015-12-07 15:14
Ok, that's great. I think I know what to do now. Thanks for help.
The only thing is, that maybe it shouldn't change the class name of the content container without it? Or maybe just comment pointing out that changing the config in the initializer file is not enough to make it work.

**Comment by ardahaal** [comment] 2015-12-07 15:27
FYI https://github.com/Sology/smart_listing#more-customization
Your problem is solved using smart_listing from github on commit `68bee13e0489b4a09a8270da3f43e56f5d2f20c9` (2 commits behind)
Turns out I found bigger bug thanks to You. I'll update You when we finish working on this.

**Comment by ardahaal** [comment] 2015-12-07 15:51
Ok, fixed and tested. Please use github (rubygems are not updated yet)
`gem 'smart_listing', git: 'https://github.com/Sology/smart_listing'`

**Comment by ardahaal** [comment] 2015-12-10 08:29
@ZebThan can I close this now? Everything good?

**Comment by ZebThan** [comment] 2015-12-10 09:11
Yes, everything works perfectly.

**Closed** 2015-12-10 09:12 UTC
